// Built-in food database.
// Values are per listed serving and are approximate averages for home-style
// preparation. Restaurant versions are often 20–50% higher in fat/calories.
// Fields: name, serving, cal (kcal), p (protein g), c (carbs g), f (fat g), cat
const FOODS = [
  // ---------- Breads ----------
  { name: "Roti / Chapati (plain)", serving: "1 medium (40 g)", cal: 120, p: 3.5, c: 18, f: 3.7, cat: "Breads" },
  { name: "Phulka (no ghee)", serving: "1 medium (30 g)", cal: 85, p: 3, c: 17, f: 0.5, cat: "Breads" },
  { name: "Roti with ghee", serving: "1 medium", cal: 155, p: 3.5, c: 18, f: 7.5, cat: "Breads" },
  { name: "Plain Paratha", serving: "1 piece (60 g)", cal: 210, p: 4.5, c: 26, f: 10, cat: "Breads" },
  { name: "Aloo Paratha", serving: "1 piece (120 g)", cal: 290, p: 6, c: 40, f: 12, cat: "Breads" },
  { name: "Gobi Paratha", serving: "1 piece (120 g)", cal: 260, p: 6, c: 34, f: 11, cat: "Breads" },
  { name: "Paneer Paratha", serving: "1 piece (120 g)", cal: 320, p: 11, c: 32, f: 16, cat: "Breads" },
  { name: "Methi Thepla", serving: "1 piece (40 g)", cal: 120, p: 3, c: 15, f: 5.5, cat: "Breads" },
  { name: "Puri", serving: "1 piece (25 g)", cal: 100, p: 1.8, c: 11, f: 5.5, cat: "Breads" },
  { name: "Bhatura", serving: "1 piece (80 g)", cal: 300, p: 6, c: 38, f: 14, cat: "Breads" },
  { name: "Plain Naan", serving: "1 piece (90 g)", cal: 260, p: 8, c: 45, f: 5, cat: "Breads" },
  { name: "Butter Naan", serving: "1 piece (100 g)", cal: 320, p: 8, c: 46, f: 11, cat: "Breads" },
  { name: "Garlic Naan", serving: "1 piece (100 g)", cal: 330, p: 8.5, c: 47, f: 12, cat: "Breads" },
  { name: "Tandoori Roti", serving: "1 piece (60 g)", cal: 150, p: 5, c: 30, f: 1, cat: "Breads" },
  { name: "Kulcha", serving: "1 piece (80 g)", cal: 240, p: 6.5, c: 40, f: 5.5, cat: "Breads" },
  { name: "Jowar Bhakri", serving: "1 piece (50 g)", cal: 140, p: 4, c: 29, f: 1, cat: "Breads" },
  { name: "Bajra Roti", serving: "1 piece (50 g)", cal: 150, p: 4.5, c: 28, f: 2.5, cat: "Breads" },
  { name: "Makki di Roti", serving: "1 piece (60 g)", cal: 190, p: 4, c: 30, f: 6, cat: "Breads" },
  { name: "Ragi Roti", serving: "1 piece (50 g)", cal: 140, p: 3.5, c: 27, f: 2, cat: "Breads" },
  { name: "Missi Roti", serving: "1 piece (60 g)", cal: 170, p: 6.5, c: 25, f: 5, cat: "Breads" },
  { name: "Kerala Parotta", serving: "1 piece (80 g)", cal: 290, p: 5.5, c: 38, f: 13, cat: "Breads" },
  { name: "Rumali Roti", serving: "1 piece (50 g)", cal: 145, p: 4, c: 28, f: 1.8, cat: "Breads" },
  { name: "Bread slice (white)", serving: "1 slice (25 g)", cal: 67, p: 2.2, c: 12.5, f: 0.8, cat: "Breads" },
  { name: "Bread slice (brown/whole wheat)", serving: "1 slice (28 g)", cal: 70, p: 3.5, c: 12, f: 1, cat: "Breads" },
  { name: "Pav", serving: "1 piece (40 g)", cal: 110, p: 3.5, c: 21, f: 1.5, cat: "Breads" },

  // ---------- Rice ----------
  { name: "Steamed White Rice", serving: "1 katori (150 g cooked)", cal: 195, p: 4, c: 43, f: 0.4, cat: "Rice" },
  { name: "Brown Rice", serving: "1 katori (150 g cooked)", cal: 170, p: 3.8, c: 35, f: 1.4, cat: "Rice" },
  { name: "Jeera Rice", serving: "1 katori (150 g)", cal: 240, p: 4, c: 42, f: 6, cat: "Rice" },
  { name: "Veg Pulao", serving: "1 katori (150 g)", cal: 250, p: 5, c: 40, f: 8, cat: "Rice" },
  { name: "Veg Biryani", serving: "1 plate (250 g)", cal: 420, p: 9, c: 62, f: 15, cat: "Rice" },
  { name: "Chicken Biryani", serving: "1 plate (300 g)", cal: 550, p: 26, c: 62, f: 21, cat: "Rice" },
  { name: "Mutton Biryani", serving: "1 plate (300 g)", cal: 620, p: 27, c: 60, f: 29, cat: "Rice" },
  { name: "Egg Biryani", serving: "1 plate (300 g)", cal: 500, p: 18, c: 64, f: 18, cat: "Rice" },
  { name: "Hyderabadi Dum Biryani (chicken)", serving: "1 plate (350 g)", cal: 650, p: 30, c: 70, f: 26, cat: "Rice" },
  { name: "Curd Rice", serving: "1 katori (200 g)", cal: 230, p: 6, c: 36, f: 6.5, cat: "Rice" },
  { name: "Lemon Rice", serving: "1 katori (150 g)", cal: 250, p: 4.5, c: 40, f: 8, cat: "Rice" },
  { name: "Tamarind Rice (Puliyogare)", serving: "1 katori (150 g)", cal: 270, p: 4.5, c: 42, f: 9, cat: "Rice" },
  { name: "Bisi Bele Bath", serving: "1 katori (200 g)", cal: 300, p: 8, c: 45, f: 9, cat: "Rice" },
  { name: "Khichdi (moong dal)", serving: "1 katori (200 g)", cal: 240, p: 9, c: 38, f: 5.5, cat: "Rice" },
  { name: "Pongal (Ven Pongal)", serving: "1 katori (200 g)", cal: 300, p: 8, c: 40, f: 12, cat: "Rice" },
  { name: "Veg Fried Rice", serving: "1 plate (250 g)", cal: 400, p: 8, c: 60, f: 14, cat: "Rice" },
  { name: "Egg Fried Rice", serving: "1 plate (250 g)", cal: 430, p: 13, c: 58, f: 16, cat: "Rice" },
  { name: "Rajma Chawal", serving: "1 plate (350 g)", cal: 450, p: 15, c: 75, f: 9, cat: "Rice" },

  // ---------- Dals & Legumes ----------
  { name: "Toor Dal (plain, tempered)", serving: "1 katori (150 ml)", cal: 150, p: 8, c: 20, f: 4, cat: "Dals" },
  { name: "Dal Tadka", serving: "1 katori (150 ml)", cal: 180, p: 8.5, c: 20, f: 7.5, cat: "Dals" },
  { name: "Dal Fry", serving: "1 katori (150 ml)", cal: 190, p: 8.5, c: 21, f: 8, cat: "Dals" },
  { name: "Dal Makhani", serving: "1 katori (150 ml)", cal: 280, p: 10, c: 24, f: 16, cat: "Dals" },
  { name: "Moong Dal", serving: "1 katori (150 ml)", cal: 140, p: 9, c: 19, f: 3, cat: "Dals" },
  { name: "Masoor Dal", serving: "1 katori (150 ml)", cal: 150, p: 9, c: 20, f: 3.5, cat: "Dals" },
  { name: "Chana Dal", serving: "1 katori (150 ml)", cal: 190, p: 10, c: 25, f: 5.5, cat: "Dals" },
  { name: "Sambar", serving: "1 katori (150 ml)", cal: 130, p: 5.5, c: 17, f: 4.5, cat: "Dals" },
  { name: "Rasam", serving: "1 katori (150 ml)", cal: 60, p: 2, c: 8, f: 2, cat: "Dals" },
  { name: "Rajma (curry)", serving: "1 katori (150 g)", cal: 210, p: 10, c: 28, f: 6.5, cat: "Dals" },
  { name: "Chole / Chana Masala", serving: "1 katori (150 g)", cal: 240, p: 10, c: 30, f: 9, cat: "Dals" },
  { name: "Kadhi Pakora", serving: "1 katori (150 ml)", cal: 200, p: 6, c: 15, f: 13, cat: "Dals" },
  { name: "Gujarati Kadhi", serving: "1 katori (150 ml)", cal: 110, p: 4, c: 10, f: 6, cat: "Dals" },
  { name: "Lobia (black-eyed peas curry)", serving: "1 katori (150 g)", cal: 190, p: 10, c: 26, f: 5, cat: "Dals" },
  { name: "Kala Chana (curry)", serving: "1 katori (150 g)", cal: 220, p: 11, c: 30, f: 6.5, cat: "Dals" },
  { name: "Usal / Misal (without farsan)", serving: "1 katori (150 g)", cal: 200, p: 10, c: 26, f: 6.5, cat: "Dals" },
  { name: "Sprouts Salad (moong)", serving: "1 katori (100 g)", cal: 110, p: 8, c: 18, f: 1, cat: "Dals" },

  // ---------- Veg Curries & Sabzi ----------
  { name: "Paneer Butter Masala", serving: "1 katori (150 g)", cal: 350, p: 13, c: 12, f: 28, cat: "Veg Curries" },
  { name: "Palak Paneer", serving: "1 katori (150 g)", cal: 260, p: 13, c: 9, f: 19, cat: "Veg Curries" },
  { name: "Kadai Paneer", serving: "1 katori (150 g)", cal: 300, p: 13, c: 10, f: 23, cat: "Veg Curries" },
  { name: "Matar Paneer", serving: "1 katori (150 g)", cal: 270, p: 12, c: 14, f: 18, cat: "Veg Curries" },
  { name: "Shahi Paneer", serving: "1 katori (150 g)", cal: 370, p: 13, c: 13, f: 30, cat: "Veg Curries" },
  { name: "Paneer Bhurji", serving: "1 katori (120 g)", cal: 290, p: 16, c: 7, f: 22, cat: "Veg Curries" },
  { name: "Aloo Gobi", serving: "1 katori (150 g)", cal: 160, p: 3.5, c: 18, f: 8.5, cat: "Veg Curries" },
  { name: "Jeera Aloo", serving: "1 katori (150 g)", cal: 190, p: 3, c: 25, f: 9, cat: "Veg Curries" },
  { name: "Aloo Matar", serving: "1 katori (150 g)", cal: 180, p: 5, c: 22, f: 8, cat: "Veg Curries" },
  { name: "Dum Aloo", serving: "1 katori (150 g)", cal: 230, p: 3.5, c: 24, f: 13, cat: "Veg Curries" },
  { name: "Bhindi Masala / Fry", serving: "1 katori (120 g)", cal: 150, p: 3, c: 12, f: 10, cat: "Veg Curries" },
  { name: "Baingan Bharta", serving: "1 katori (150 g)", cal: 140, p: 3, c: 13, f: 8.5, cat: "Veg Curries" },
  { name: "Mix Veg Curry", serving: "1 katori (150 g)", cal: 170, p: 4, c: 16, f: 10, cat: "Veg Curries" },
  { name: "Veg Kurma", serving: "1 katori (150 g)", cal: 210, p: 4, c: 15, f: 15, cat: "Veg Curries" },
  { name: "Malai Kofta", serving: "1 katori (150 g)", cal: 380, p: 8, c: 22, f: 29, cat: "Veg Curries" },
  { name: "Navratan Korma", serving: "1 katori (150 g)", cal: 300, p: 6, c: 20, f: 22, cat: "Veg Curries" },
  { name: "Sarson ka Saag", serving: "1 katori (150 g)", cal: 170, p: 5, c: 10, f: 12, cat: "Veg Curries" },
  { name: "Methi Malai Matar", serving: "1 katori (150 g)", cal: 260, p: 7, c: 14, f: 20, cat: "Veg Curries" },
  { name: "Cabbage Sabzi / Poriyal", serving: "1 katori (120 g)", cal: 90, p: 2, c: 9, f: 5, cat: "Veg Curries" },
  { name: "Beans Poriyal / Thoran", serving: "1 katori (120 g)", cal: 110, p: 3, c: 10, f: 6.5, cat: "Veg Curries" },
  { name: "Lauki (bottle gourd) Sabzi", serving: "1 katori (150 g)", cal: 80, p: 1.5, c: 8, f: 4.5, cat: "Veg Curries" },
  { name: "Tinda / Turai Sabzi", serving: "1 katori (150 g)", cal: 85, p: 1.5, c: 8, f: 5, cat: "Veg Curries" },
  { name: "Karela Fry", serving: "1 katori (100 g)", cal: 130, p: 2.5, c: 10, f: 9, cat: "Veg Curries" },
  { name: "Avial", serving: "1 katori (150 g)", cal: 170, p: 3, c: 12, f: 12, cat: "Veg Curries" },
  { name: "Mushroom Masala", serving: "1 katori (150 g)", cal: 170, p: 5, c: 10, f: 12, cat: "Veg Curries" },
  { name: "Soya Chunks Curry", serving: "1 katori (150 g)", cal: 220, p: 18, c: 14, f: 10, cat: "Veg Curries" },
  { name: "Pav Bhaji (bhaji only)", serving: "1 katori (200 g)", cal: 280, p: 5, c: 30, f: 16, cat: "Veg Curries" },

  // ---------- Non-Veg ----------
  { name: "Butter Chicken", serving: "1 katori (150 g)", cal: 340, p: 22, c: 9, f: 24, cat: "Non-Veg" },
  { name: "Chicken Curry (home-style)", serving: "1 katori (150 g)", cal: 250, p: 22, c: 6, f: 15, cat: "Non-Veg" },
  { name: "Chicken Tikka Masala", serving: "1 katori (150 g)", cal: 300, p: 24, c: 10, f: 18, cat: "Non-Veg" },
  { name: "Kadai Chicken", serving: "1 katori (150 g)", cal: 280, p: 23, c: 8, f: 17, cat: "Non-Veg" },
  { name: "Chicken Chettinad", serving: "1 katori (150 g)", cal: 290, p: 23, c: 7, f: 19, cat: "Non-Veg" },
  { name: "Chicken Tikka (dry)", serving: "6 pieces (150 g)", cal: 230, p: 32, c: 5, f: 9, cat: "Non-Veg" },
  { name: "Tandoori Chicken", serving: "1 leg quarter (200 g)", cal: 300, p: 38, c: 4, f: 14, cat: "Non-Veg" },
  { name: "Chicken 65", serving: "1 plate (150 g)", cal: 380, p: 25, c: 15, f: 24, cat: "Non-Veg" },
  { name: "Chilli Chicken (dry)", serving: "1 plate (150 g)", cal: 340, p: 22, c: 16, f: 21, cat: "Non-Veg" },
  { name: "Grilled Chicken Breast", serving: "100 g", cal: 165, p: 31, c: 0, f: 3.6, cat: "Non-Veg" },
  { name: "Chicken Seekh Kebab", serving: "2 pieces (100 g)", cal: 210, p: 18, c: 4, f: 14, cat: "Non-Veg" },
  { name: "Mutton Curry / Rogan Josh", serving: "1 katori (150 g)", cal: 330, p: 22, c: 6, f: 24, cat: "Non-Veg" },
  { name: "Keema Matar", serving: "1 katori (150 g)", cal: 300, p: 20, c: 10, f: 20, cat: "Non-Veg" },
  { name: "Fish Curry", serving: "1 katori (150 g)", cal: 220, p: 20, c: 6, f: 13, cat: "Non-Veg" },
  { name: "Fish Fry (rava/masala)", serving: "1 piece (100 g)", cal: 230, p: 20, c: 8, f: 13, cat: "Non-Veg" },
  { name: "Prawn Curry", serving: "1 katori (150 g)", cal: 220, p: 20, c: 7, f: 12, cat: "Non-Veg" },

  // ---------- Eggs ----------
  { name: "Boiled Egg", serving: "1 large", cal: 78, p: 6.3, c: 0.6, f: 5.3, cat: "Eggs" },
  { name: "Boiled Eggs (2)", serving: "2 large", cal: 156, p: 12.6, c: 1.2, f: 10.6, cat: "Eggs" },
  { name: "Egg White (boiled)", serving: "1 large", cal: 17, p: 3.6, c: 0.2, f: 0.1, cat: "Eggs" },
  { name: "Poached Egg", serving: "1 large", cal: 72, p: 6.3, c: 0.4, f: 5, cat: "Eggs" },
  { name: "Fried Egg / Half Fry / Bullseye", serving: "1 egg (1/2 tsp oil)", cal: 100, p: 6.3, c: 0.6, f: 8, cat: "Eggs" },
  { name: "Plain Omelette (1 egg)", serving: "1 egg (1/2 tsp oil)", cal: 100, p: 6.3, c: 0.6, f: 8, cat: "Eggs" },
  { name: "Plain Omelette (2 eggs)", serving: "2 eggs (1 tsp oil)", cal: 190, p: 12.6, c: 1.2, f: 15, cat: "Eggs" },
  { name: "Masala Omelette (1 egg)", serving: "1 egg", cal: 110, p: 6.6, c: 1.8, f: 8.3, cat: "Eggs" },
  { name: "Masala Omelette", serving: "2 eggs", cal: 210, p: 13, c: 3, f: 16, cat: "Eggs" },
  { name: "Cheese Omelette", serving: "2 eggs", cal: 270, p: 17, c: 2, f: 21, cat: "Eggs" },
  { name: "Egg White Omelette", serving: "3 egg whites", cal: 75, p: 11, c: 1.5, f: 2.5, cat: "Eggs" },
  { name: "Scrambled Eggs (with butter)", serving: "2 eggs", cal: 200, p: 13, c: 2, f: 15, cat: "Eggs" },
  { name: "Egg Bhurji", serving: "2 eggs", cal: 220, p: 13, c: 4, f: 17, cat: "Eggs" },
  { name: "Anda Bhurji Pav", serving: "2 eggs + 2 pav", cal: 440, p: 20, c: 46, f: 20, cat: "Eggs" },
  { name: "Bread Omelette", serving: "2 eggs + 2 slices", cal: 330, p: 17, c: 26, f: 17, cat: "Eggs" },
  { name: "Egg Curry", serving: "2 eggs + gravy", cal: 280, p: 14, c: 8, f: 21, cat: "Eggs" },
  { name: "Egg Sandwich", serving: "1 sandwich", cal: 300, p: 13, c: 30, f: 14, cat: "Eggs" },
  { name: "Egg Roll / Kathi Roll", serving: "1 roll", cal: 380, p: 14, c: 40, f: 18, cat: "Eggs" },
  { name: "Anda Paratha / Egg Paratha", serving: "1 piece", cal: 330, p: 12, c: 30, f: 18, cat: "Eggs" },
  { name: "Egg Dosa", serving: "1 piece", cal: 230, p: 9, c: 23, f: 11, cat: "Eggs" },
  { name: "Egg Maggi", serving: "1 pack + 1 egg", cal: 390, p: 13, c: 43, f: 18, cat: "Eggs" },

  // ---------- South Indian / Breakfast ----------
  { name: "Idli", serving: "1 piece (40 g)", cal: 60, p: 2, c: 12, f: 0.3, cat: "Breakfast" },
  { name: "Plain Dosa", serving: "1 medium", cal: 135, p: 3, c: 22, f: 3.7, cat: "Breakfast" },
  { name: "Masala Dosa", serving: "1 piece", cal: 300, p: 6, c: 42, f: 12, cat: "Breakfast" },
  { name: "Ghee Roast Dosa", serving: "1 piece", cal: 280, p: 4, c: 33, f: 14, cat: "Breakfast" },
  { name: "Rava Dosa", serving: "1 piece", cal: 200, p: 4, c: 28, f: 8, cat: "Breakfast" },
  { name: "Onion Uttapam", serving: "1 piece", cal: 210, p: 5, c: 33, f: 6, cat: "Breakfast" },
  { name: "Medu Vada", serving: "1 piece (50 g)", cal: 140, p: 4.5, c: 13, f: 8, cat: "Breakfast" },
  { name: "Appam", serving: "1 piece", cal: 120, p: 2, c: 22, f: 2.5, cat: "Breakfast" },
  { name: "Puttu", serving: "1 cylinder (100 g)", cal: 190, p: 4, c: 38, f: 2.5, cat: "Breakfast" },
  { name: "Pesarattu", serving: "1 piece", cal: 170, p: 8, c: 24, f: 4.5, cat: "Breakfast" },
  { name: "Upma (rava)", serving: "1 katori (150 g)", cal: 230, p: 5, c: 33, f: 8.5, cat: "Breakfast" },
  { name: "Poha", serving: "1 plate (150 g)", cal: 250, p: 5, c: 40, f: 8, cat: "Breakfast" },
  { name: "Sabudana Khichdi", serving: "1 plate (150 g)", cal: 330, p: 4.5, c: 50, f: 12, cat: "Breakfast" },
  { name: "Besan Chilla", serving: "1 piece", cal: 140, p: 6.5, c: 15, f: 6, cat: "Breakfast" },
  { name: "Moong Dal Chilla", serving: "1 piece", cal: 120, p: 7, c: 15, f: 3.5, cat: "Breakfast" },
  { name: "Oats Upma / Masala Oats", serving: "1 katori (150 g)", cal: 180, p: 6, c: 28, f: 5, cat: "Breakfast" },
  { name: "Dhokla (khaman)", serving: "2 pieces (80 g)", cal: 160, p: 6, c: 22, f: 5, cat: "Breakfast" },
  { name: "Coconut Chutney", serving: "2 tbsp (30 g)", cal: 70, p: 1, c: 3, f: 6.5, cat: "Breakfast" },
  { name: "Tomato / Onion Chutney", serving: "2 tbsp (30 g)", cal: 40, p: 0.5, c: 4, f: 2.5, cat: "Breakfast" },
  { name: "Mint-Coriander Chutney", serving: "1 tbsp (15 g)", cal: 10, p: 0.3, c: 1.5, f: 0.2, cat: "Breakfast" },

  // ---------- Snacks & Street Food ----------
  { name: "Samosa", serving: "1 piece (75 g)", cal: 260, p: 4, c: 28, f: 15, cat: "Snacks" },
  { name: "Kachori", serving: "1 piece (60 g)", cal: 220, p: 4.5, c: 22, f: 13, cat: "Snacks" },
  { name: "Onion Pakora / Bhaji", serving: "4 pieces (80 g)", cal: 260, p: 5, c: 24, f: 16, cat: "Snacks" },
  { name: "Paneer Pakora", serving: "4 pieces (100 g)", cal: 320, p: 13, c: 15, f: 23, cat: "Snacks" },
  { name: "Vada Pav", serving: "1 piece", cal: 290, p: 6, c: 40, f: 12, cat: "Snacks" },
  { name: "Pav Bhaji (2 pav + bhaji)", serving: "1 plate", cal: 520, p: 12, c: 72, f: 20, cat: "Snacks" },
  { name: "Pani Puri / Golgappa", serving: "6 pieces", cal: 210, p: 4, c: 34, f: 6.5, cat: "Snacks" },
  { name: "Bhel Puri", serving: "1 plate (150 g)", cal: 280, p: 6, c: 45, f: 8.5, cat: "Snacks" },
  { name: "Sev Puri", serving: "6 pieces", cal: 330, p: 6, c: 38, f: 17, cat: "Snacks" },
  { name: "Dahi Puri", serving: "6 pieces", cal: 300, p: 7, c: 40, f: 12, cat: "Snacks" },
  { name: "Aloo Tikki", serving: "2 pieces (120 g)", cal: 260, p: 4, c: 32, f: 13, cat: "Snacks" },
  { name: "Chole Bhature", serving: "1 plate (2 bhature)", cal: 850, p: 22, c: 106, f: 37, cat: "Snacks" },
  { name: "Misal Pav", serving: "1 plate (2 pav)", cal: 520, p: 18, c: 70, f: 19, cat: "Snacks" },
  { name: "Dabeli", serving: "1 piece", cal: 270, p: 5, c: 40, f: 10, cat: "Snacks" },
  { name: "Veg Momos (steamed)", serving: "6 pieces", cal: 220, p: 6, c: 36, f: 5, cat: "Snacks" },
  { name: "Chicken Momos (steamed)", serving: "6 pieces", cal: 280, p: 15, c: 34, f: 9, cat: "Snacks" },
  { name: "Veg Frankie / Kathi Roll", serving: "1 roll", cal: 350, p: 8, c: 45, f: 15, cat: "Snacks" },
  { name: "Chicken Kathi Roll", serving: "1 roll", cal: 420, p: 22, c: 42, f: 18, cat: "Snacks" },
  { name: "Veg Sandwich (Bombay)", serving: "1 sandwich", cal: 250, p: 6, c: 34, f: 10, cat: "Snacks" },
  { name: "Veg Hakka Noodles", serving: "1 plate (250 g)", cal: 420, p: 9, c: 60, f: 16, cat: "Snacks" },
  { name: "Maggi Noodles", serving: "1 pack (70 g dry)", cal: 310, p: 6.5, c: 43, f: 12.5, cat: "Snacks" },
  { name: "Gobi Manchurian (dry)", serving: "1 plate (150 g)", cal: 320, p: 5, c: 32, f: 19, cat: "Snacks" },
  { name: "Namkeen / Bhujia", serving: "30 g (small handful)", cal: 165, p: 4.5, c: 13, f: 11, cat: "Snacks" },
  { name: "Roasted Chana", serving: "30 g", cal: 110, p: 6.5, c: 17, f: 1.7, cat: "Snacks" },
  { name: "Makhana (roasted)", serving: "30 g", cal: 110, p: 3, c: 20, f: 1.5, cat: "Snacks" },
  { name: "Khakhra", serving: "1 piece (20 g)", cal: 80, p: 2.5, c: 12, f: 2.5, cat: "Snacks" },
  { name: "Banana Chips", serving: "30 g", cal: 160, p: 0.7, c: 17, f: 10, cat: "Snacks" },
  { name: "Murukku / Chakli", serving: "2 pieces (30 g)", cal: 160, p: 2.5, c: 17, f: 9, cat: "Snacks" },
  { name: "Marie Biscuit", serving: "2 biscuits (14 g)", cal: 60, p: 1, c: 10.5, f: 1.5, cat: "Snacks" },
  { name: "Parle-G Biscuit", serving: "4 biscuits (25 g)", cal: 115, p: 1.7, c: 19, f: 3.5, cat: "Snacks" },

  // ---------- Dairy ----------
  { name: "Milk (toned, 3% fat)", serving: "1 glass (200 ml)", cal: 120, p: 6.5, c: 9.5, f: 6, cat: "Dairy" },
  { name: "Milk (full cream)", serving: "1 glass (200 ml)", cal: 170, p: 6.5, c: 9.5, f: 12, cat: "Dairy" },
  { name: "Milk (skimmed)", serving: "1 glass (200 ml)", cal: 70, p: 7, c: 10, f: 0.2, cat: "Dairy" },
  { name: "Curd / Dahi (homemade)", serving: "1 katori (100 g)", cal: 60, p: 3.5, c: 4.5, f: 3.5, cat: "Dairy" },
  { name: "Greek Yogurt (plain)", serving: "100 g", cal: 75, p: 10, c: 4, f: 2, cat: "Dairy" },
  { name: "Paneer (raw)", serving: "100 g", cal: 265, p: 18, c: 3.5, f: 20, cat: "Dairy" },
  { name: "Low-fat Paneer", serving: "100 g", cal: 180, p: 22, c: 4, f: 8, cat: "Dairy" },
  { name: "Ghee", serving: "1 tsp (5 g)", cal: 45, p: 0, c: 0, f: 5, cat: "Dairy" },
  { name: "Butter", serving: "1 tsp (5 g)", cal: 36, p: 0, c: 0, f: 4, cat: "Dairy" },
  { name: "Cheese Slice", serving: "1 slice (20 g)", cal: 62, p: 4, c: 1, f: 4.8, cat: "Dairy" },
  { name: "Raita (cucumber/boondi)", serving: "1 katori (100 g)", cal: 80, p: 3, c: 6, f: 4.5, cat: "Dairy" },
  { name: "Buttermilk / Chaas", serving: "1 glass (200 ml)", cal: 40, p: 2, c: 3, f: 2, cat: "Dairy" },

  // ---------- Beverages ----------
  { name: "Masala Chai (with milk & sugar)", serving: "1 cup (150 ml)", cal: 90, p: 2.5, c: 12, f: 3.5, cat: "Beverages" },
  { name: "Chai (no sugar)", serving: "1 cup (150 ml)", cal: 50, p: 2.5, c: 4, f: 3, cat: "Beverages" },
  { name: "Filter Coffee (with sugar)", serving: "1 tumbler (150 ml)", cal: 100, p: 3, c: 13, f: 4, cat: "Beverages" },
  { name: "Black Coffee", serving: "1 cup", cal: 5, p: 0.3, c: 0, f: 0, cat: "Beverages" },
  { name: "Green Tea", serving: "1 cup", cal: 2, p: 0, c: 0, f: 0, cat: "Beverages" },
  { name: "Sweet Lassi", serving: "1 glass (250 ml)", cal: 260, p: 8, c: 38, f: 8, cat: "Beverages" },
  { name: "Salted Lassi", serving: "1 glass (250 ml)", cal: 120, p: 7, c: 9, f: 6.5, cat: "Beverages" },
  { name: "Mango Lassi", serving: "1 glass (250 ml)", cal: 300, p: 7, c: 50, f: 7.5, cat: "Beverages" },
  { name: "Nimbu Pani (with sugar)", serving: "1 glass (250 ml)", cal: 80, p: 0, c: 20, f: 0, cat: "Beverages" },
  { name: "Coconut Water", serving: "1 glass (250 ml)", cal: 48, p: 1.8, c: 9, f: 0.5, cat: "Beverages" },
  { name: "Sugarcane Juice", serving: "1 glass (250 ml)", cal: 180, p: 0.5, c: 45, f: 0.3, cat: "Beverages" },
  { name: "Badam Milk", serving: "1 glass (200 ml)", cal: 220, p: 7, c: 26, f: 10, cat: "Beverages" },
  { name: "Cold Drink / Soda (regular)", serving: "1 can (330 ml)", cal: 140, p: 0, c: 35, f: 0, cat: "Beverages" },
  { name: "Fresh Orange Juice", serving: "1 glass (250 ml)", cal: 110, p: 1.7, c: 26, f: 0.5, cat: "Beverages" },
  { name: "Whey Protein (1 scoop, in water)", serving: "1 scoop (30 g)", cal: 120, p: 24, c: 3, f: 1.5, cat: "Beverages" },

  // ---------- Sweets ----------
  { name: "Gulab Jamun", serving: "1 piece (40 g)", cal: 150, p: 2, c: 22, f: 6, cat: "Sweets" },
  { name: "Rasgulla", serving: "1 piece (40 g)", cal: 110, p: 2.5, c: 23, f: 1, cat: "Sweets" },
  { name: "Rasmalai", serving: "1 piece with rabri", cal: 190, p: 6, c: 22, f: 9, cat: "Sweets" },
  { name: "Jalebi", serving: "2 pieces (50 g)", cal: 200, p: 1.5, c: 33, f: 7.5, cat: "Sweets" },
  { name: "Kaju Katli", serving: "1 piece (15 g)", cal: 65, p: 1.5, c: 7, f: 3.5, cat: "Sweets" },
  { name: "Besan Ladoo", serving: "1 piece (35 g)", cal: 170, p: 3, c: 18, f: 10, cat: "Sweets" },
  { name: "Motichoor Ladoo", serving: "1 piece (35 g)", cal: 160, p: 2, c: 22, f: 7.5, cat: "Sweets" },
  { name: "Gajar Halwa", serving: "1 katori (100 g)", cal: 280, p: 5, c: 35, f: 14, cat: "Sweets" },
  { name: "Sooji Halwa / Sheera", serving: "1 katori (100 g)", cal: 320, p: 4, c: 42, f: 15, cat: "Sweets" },
  { name: "Kheer / Payasam", serving: "1 katori (150 g)", cal: 250, p: 7, c: 36, f: 8.5, cat: "Sweets" },
  { name: "Barfi (milk)", serving: "1 piece (30 g)", cal: 130, p: 3, c: 16, f: 6, cat: "Sweets" },
  { name: "Mysore Pak", serving: "1 piece (30 g)", cal: 170, p: 2, c: 15, f: 11.5, cat: "Sweets" },
  { name: "Sandesh", serving: "1 piece (30 g)", cal: 95, p: 3.5, c: 13, f: 3.5, cat: "Sweets" },
  { name: "Kulfi", serving: "1 stick (60 g)", cal: 170, p: 4, c: 18, f: 9, cat: "Sweets" },
  { name: "Shrikhand", serving: "1 katori (100 g)", cal: 250, p: 6, c: 38, f: 8, cat: "Sweets" },
  { name: "Modak (steamed)", serving: "1 piece (40 g)", cal: 110, p: 1.5, c: 17, f: 4, cat: "Sweets" },
  { name: "Sugar", serving: "1 tsp (5 g)", cal: 20, p: 0, c: 5, f: 0, cat: "Sweets" },
  { name: "Jaggery", serving: "1 tsp (7 g)", cal: 27, p: 0, c: 7, f: 0, cat: "Sweets" },

  // ---------- Fruits ----------
  { name: "Banana", serving: "1 medium (120 g)", cal: 105, p: 1.3, c: 27, f: 0.4, cat: "Fruits" },
  { name: "Apple", serving: "1 medium (180 g)", cal: 95, p: 0.5, c: 25, f: 0.3, cat: "Fruits" },
  { name: "Mango", serving: "1 cup sliced (165 g)", cal: 100, p: 1.4, c: 25, f: 0.6, cat: "Fruits" },
  { name: "Papaya", serving: "1 cup (145 g)", cal: 62, p: 0.7, c: 16, f: 0.4, cat: "Fruits" },
  { name: "Guava", serving: "1 medium (100 g)", cal: 68, p: 2.6, c: 14, f: 1, cat: "Fruits" },
  { name: "Orange", serving: "1 medium (130 g)", cal: 62, p: 1.2, c: 15, f: 0.2, cat: "Fruits" },
  { name: "Mosambi (sweet lime)", serving: "1 medium (130 g)", cal: 55, p: 1, c: 13, f: 0.2, cat: "Fruits" },
  { name: "Watermelon", serving: "1 cup (150 g)", cal: 45, p: 0.9, c: 11, f: 0.2, cat: "Fruits" },
  { name: "Pomegranate", serving: "1/2 cup arils (85 g)", cal: 72, p: 1.4, c: 16, f: 1, cat: "Fruits" },
  { name: "Grapes", serving: "1 cup (150 g)", cal: 104, p: 1.1, c: 27, f: 0.2, cat: "Fruits" },
  { name: "Chikoo (sapota)", serving: "1 medium (100 g)", cal: 83, p: 0.4, c: 20, f: 1.1, cat: "Fruits" },
  { name: "Pineapple", serving: "1 cup (165 g)", cal: 82, p: 0.9, c: 22, f: 0.2, cat: "Fruits" },
  { name: "Dates (dried)", serving: "2 pieces (16 g)", cal: 45, p: 0.4, c: 12, f: 0, cat: "Fruits" },

  // ---------- Nuts, Seeds & Basics ----------
  { name: "Almonds", serving: "10 pieces (12 g)", cal: 70, p: 2.5, c: 2.5, f: 6, cat: "Nuts & Basics" },
  { name: "Cashews", serving: "10 pieces (15 g)", cal: 85, p: 2.7, c: 4.5, f: 6.6, cat: "Nuts & Basics" },
  { name: "Walnuts", serving: "4 halves (8 g)", cal: 52, p: 1.2, c: 1.1, f: 5.2, cat: "Nuts & Basics" },
  { name: "Peanuts (roasted)", serving: "30 g", cal: 170, p: 7.5, c: 5, f: 14.5, cat: "Nuts & Basics" },
  { name: "Peanut Butter", serving: "1 tbsp (16 g)", cal: 95, p: 3.5, c: 3, f: 8, cat: "Nuts & Basics" },
  { name: "Flax / Chia Seeds", serving: "1 tbsp (10 g)", cal: 50, p: 1.8, c: 3, f: 3.5, cat: "Nuts & Basics" },
  { name: "Cooking Oil", serving: "1 tsp (5 ml)", cal: 45, p: 0, c: 0, f: 5, cat: "Nuts & Basics" },
  { name: "Oats (dry)", serving: "40 g", cal: 150, p: 5, c: 27, f: 2.7, cat: "Nuts & Basics" },
  { name: "Cornflakes", serving: "30 g", cal: 113, p: 2, c: 25, f: 0.3, cat: "Nuts & Basics" },
  { name: "Tofu", serving: "100 g", cal: 145, p: 15.5, c: 3.5, f: 8.7, cat: "Nuts & Basics" },
  { name: "Soya Chunks (dry)", serving: "30 g", cal: 104, p: 15.6, c: 9.9, f: 0.2, cat: "Nuts & Basics" },
  { name: "Green Salad (cucumber, tomato, onion)", serving: "1 bowl (150 g)", cal: 35, p: 1.5, c: 7, f: 0.2, cat: "Nuts & Basics" },
  { name: "Papad (roasted)", serving: "1 piece", cal: 35, p: 2.5, c: 6, f: 0.3, cat: "Nuts & Basics" },
  { name: "Papad (fried)", serving: "1 piece", cal: 80, p: 2.5, c: 6, f: 5, cat: "Nuts & Basics" },
  { name: "Pickle / Achaar", serving: "1 tsp (10 g)", cal: 25, p: 0.2, c: 1, f: 2.3, cat: "Nuts & Basics" },

  // ---------- Fast Food & Cafe ----------
  { name: "Veg Burger", serving: "1 burger", cal: 380, p: 10, c: 50, f: 15, cat: "Fast Food" },
  { name: "Chicken Burger", serving: "1 burger", cal: 450, p: 22, c: 45, f: 20, cat: "Fast Food" },
  { name: "Cheese Burger (beef/lamb)", serving: "1 burger", cal: 300, p: 15, c: 32, f: 13, cat: "Fast Food" },
  { name: "French Fries", serving: "medium (115 g)", cal: 330, p: 4, c: 42, f: 16, cat: "Fast Food" },
  { name: "French Fries (small)", serving: "small (80 g)", cal: 230, p: 3, c: 29, f: 11, cat: "Fast Food" },
  { name: "Margherita Pizza", serving: "1 slice (medium pizza)", cal: 200, p: 8, c: 25, f: 7.5, cat: "Fast Food" },
  { name: "Veg Pizza (loaded)", serving: "1 slice (medium pizza)", cal: 230, p: 9, c: 27, f: 9.5, cat: "Fast Food" },
  { name: "Chicken / Pepperoni Pizza", serving: "1 slice (medium pizza)", cal: 260, p: 12, c: 26, f: 12, cat: "Fast Food" },
  { name: "Garlic Bread", serving: "2 pieces", cal: 200, p: 4.5, c: 24, f: 9.5, cat: "Fast Food" },
  { name: "Fried Chicken", serving: "1 piece (drumstick/thigh)", cal: 280, p: 18, c: 9, f: 19, cat: "Fast Food" },
  { name: "Chicken Nuggets", serving: "6 pieces", cal: 270, p: 14, c: 16, f: 17, cat: "Fast Food" },
  { name: "Chicken Wrap", serving: "1 wrap", cal: 450, p: 24, c: 45, f: 19, cat: "Fast Food" },
  { name: "Veg Sub Sandwich (6 inch)", serving: "1 sub", cal: 300, p: 11, c: 50, f: 5, cat: "Fast Food" },
  { name: "Chicken Sub Sandwich (6 inch)", serving: "1 sub", cal: 380, p: 24, c: 46, f: 10, cat: "Fast Food" },
  { name: "Grilled Cheese Sandwich", serving: "1 sandwich", cal: 370, p: 14, c: 30, f: 22, cat: "Fast Food" },
  { name: "Club Sandwich", serving: "1 sandwich", cal: 550, p: 28, c: 45, f: 28, cat: "Fast Food" },
  { name: "Shawarma (chicken)", serving: "1 roll", cal: 480, p: 26, c: 45, f: 21, cat: "Fast Food" },
  { name: "Hot Dog", serving: "1 piece", cal: 290, p: 10, c: 24, f: 17, cat: "Fast Food" },
  { name: "Tacos (chicken)", serving: "2 tacos", cal: 340, p: 20, c: 30, f: 15, cat: "Fast Food" },
  { name: "Nachos with Cheese", serving: "1 plate (150 g)", cal: 500, p: 11, c: 50, f: 28, cat: "Fast Food" },

  // ---------- Western & Continental ----------
  { name: "Pasta in White Sauce (Alfredo)", serving: "1 plate (250 g)", cal: 520, p: 15, c: 55, f: 26, cat: "Western" },
  { name: "Pasta in Red Sauce (Arrabbiata)", serving: "1 plate (250 g)", cal: 380, p: 12, c: 62, f: 9, cat: "Western" },
  { name: "Mac and Cheese", serving: "1 bowl (200 g)", cal: 420, p: 16, c: 45, f: 19, cat: "Western" },
  { name: "Spaghetti Bolognese", serving: "1 plate (300 g)", cal: 480, p: 24, c: 58, f: 16, cat: "Western" },
  { name: "Caesar Salad (with dressing)", serving: "1 bowl", cal: 330, p: 9, c: 14, f: 27, cat: "Western" },
  { name: "Grilled Chicken Salad", serving: "1 bowl", cal: 280, p: 30, c: 12, f: 12, cat: "Western" },
  { name: "Burrito Bowl (chicken)", serving: "1 bowl", cal: 620, p: 38, c: 70, f: 20, cat: "Western" },
  { name: "Pancakes (with syrup)", serving: "2 pancakes", cal: 350, p: 7, c: 60, f: 9, cat: "Western" },
  { name: "Toast with Butter", serving: "2 slices", cal: 210, p: 4.5, c: 25, f: 9.5, cat: "Western" },
  { name: "Toast with Jam", serving: "2 slices", cal: 210, p: 4.5, c: 37, f: 2, cat: "Western" },
  { name: "Muesli with Milk", serving: "1 bowl (40 g + 150 ml)", cal: 240, p: 9, c: 37, f: 6, cat: "Western" },
  { name: "Overnight Oats", serving: "1 jar (250 g)", cal: 320, p: 13, c: 45, f: 9, cat: "Western" },
  { name: "Soup (tomato / veg, restaurant)", serving: "1 bowl (250 ml)", cal: 130, p: 3, c: 18, f: 5, cat: "Western" },
  { name: "Sweet Corn Soup", serving: "1 bowl (250 ml)", cal: 140, p: 4, c: 25, f: 3, cat: "Western" },
  { name: "Hot and Sour Soup", serving: "1 bowl (250 ml)", cal: 110, p: 5, c: 13, f: 4, cat: "Western" },
  { name: "Sushi Roll (veg/fish)", serving: "6 pieces", cal: 250, p: 8, c: 45, f: 4, cat: "Western" },

  // ---------- Bakery & Desserts ----------
  { name: "Chocolate Cake", serving: "1 slice (80 g)", cal: 350, p: 4, c: 45, f: 17, cat: "Bakery & Desserts" },
  { name: "Cheesecake", serving: "1 slice (100 g)", cal: 400, p: 7, c: 32, f: 28, cat: "Bakery & Desserts" },
  { name: "Brownie", serving: "1 piece (60 g)", cal: 270, p: 3, c: 35, f: 14, cat: "Bakery & Desserts" },
  { name: "Pastry (cream)", serving: "1 piece (80 g)", cal: 300, p: 3.5, c: 35, f: 16, cat: "Bakery & Desserts" },
  { name: "Muffin (chocolate / blueberry)", serving: "1 muffin (110 g)", cal: 420, p: 6, c: 55, f: 20, cat: "Bakery & Desserts" },
  { name: "Croissant (butter)", serving: "1 piece (60 g)", cal: 250, p: 5, c: 27, f: 13, cat: "Bakery & Desserts" },
  { name: "Donut (glazed)", serving: "1 piece", cal: 260, p: 3.5, c: 31, f: 14, cat: "Bakery & Desserts" },
  { name: "Veg Puff", serving: "1 piece (80 g)", cal: 280, p: 4.5, c: 26, f: 18, cat: "Bakery & Desserts" },
  { name: "Egg / Chicken Puff", serving: "1 piece (90 g)", cal: 320, p: 9, c: 25, f: 20, cat: "Bakery & Desserts" },
  { name: "Ice Cream (vanilla)", serving: "1 scoop (65 g)", cal: 135, p: 2.3, c: 16, f: 7, cat: "Bakery & Desserts" },
  { name: "Ice Cream Cone / Cornetto", serving: "1 cone", cal: 220, p: 3, c: 28, f: 11, cat: "Bakery & Desserts" },
  { name: "Milk Chocolate", serving: "1 small bar (25 g)", cal: 135, p: 2, c: 15, f: 7.5, cat: "Bakery & Desserts" },
  { name: "Dark Chocolate (70%)", serving: "2 squares (20 g)", cal: 120, p: 1.6, c: 9, f: 8.5, cat: "Bakery & Desserts" },
  { name: "Cookies (chocolate chip)", serving: "2 cookies (30 g)", cal: 145, p: 1.7, c: 19, f: 7, cat: "Bakery & Desserts" },
  { name: "Cream Biscuits", serving: "3 biscuits (30 g)", cal: 150, p: 1.5, c: 21, f: 6.5, cat: "Bakery & Desserts" },
  { name: "Rusk / Toast biscuit", serving: "2 pieces (20 g)", cal: 80, p: 2, c: 14, f: 1.6, cat: "Bakery & Desserts" },

  // ---------- Packaged Snacks & Drinks ----------
  { name: "Potato Chips", serving: "1 small pack (28 g)", cal: 150, p: 2, c: 15, f: 9.5, cat: "Packaged & Drinks" },
  { name: "Popcorn (butter, cinema)", serving: "medium tub (60 g)", cal: 330, p: 5, c: 33, f: 20, cat: "Packaged & Drinks" },
  { name: "Popcorn (plain, air-popped)", serving: "3 cups (24 g)", cal: 90, p: 3, c: 18, f: 1, cat: "Packaged & Drinks" },
  { name: "Protein Bar", serving: "1 bar (60 g)", cal: 220, p: 20, c: 22, f: 7, cat: "Packaged & Drinks" },
  { name: "Granola Bar", serving: "1 bar (35 g)", cal: 150, p: 3, c: 22, f: 6, cat: "Packaged & Drinks" },
  { name: "Instant Cup Noodles", serving: "1 cup (70 g)", cal: 320, p: 6, c: 42, f: 14, cat: "Packaged & Drinks" },
  { name: "Cappuccino / Latte (whole milk)", serving: "regular (350 ml)", cal: 190, p: 10, c: 15, f: 10, cat: "Packaged & Drinks" },
  { name: "Cold Coffee (cafe, with sugar)", serving: "1 glass (350 ml)", cal: 300, p: 8, c: 45, f: 9, cat: "Packaged & Drinks" },
  { name: "Frappe with Whipped Cream", serving: "regular (400 ml)", cal: 400, p: 6, c: 60, f: 15, cat: "Packaged & Drinks" },
  { name: "Milkshake (chocolate/strawberry)", serving: "1 glass (350 ml)", cal: 420, p: 11, c: 62, f: 14, cat: "Packaged & Drinks" },
  { name: "Hot Chocolate", serving: "1 cup (250 ml)", cal: 220, p: 8, c: 30, f: 8, cat: "Packaged & Drinks" },
  { name: "Packaged Fruit Juice", serving: "1 glass (200 ml)", cal: 110, p: 0.5, c: 27, f: 0, cat: "Packaged & Drinks" },
  { name: "Energy Drink", serving: "1 can (250 ml)", cal: 115, p: 0, c: 28, f: 0, cat: "Packaged & Drinks" },
  { name: "Diet Soda", serving: "1 can (330 ml)", cal: 1, p: 0, c: 0, f: 0, cat: "Packaged & Drinks" },

  // ---------- Alcohol ----------
  // Most alcohol calories come from the alcohol itself (7 kcal/g), so protein + carbs + fat
  // don't add up to the calorie figure. Assumes 40% spirits unless stated.
  { name: "Beer (regular, 5%)", serving: "1 pint (330 ml)", cal: 145, p: 1.5, c: 12, f: 0, cat: "Beer & Wine" },
  { name: "Beer bottle (regular, 650 ml)", serving: "1 bottle (650 ml)", cal: 280, p: 3, c: 22, f: 0, cat: "Beer & Wine" },
  { name: "Beer can (regular, 500 ml)", serving: "1 can (500 ml)", cal: 215, p: 2, c: 17, f: 0, cat: "Beer & Wine" },
  { name: "Draught Beer (mug)", serving: "1 mug (500 ml)", cal: 215, p: 2, c: 17, f: 0, cat: "Beer & Wine" },
  { name: "Draught Beer (pitcher)", serving: "1 pitcher (1.5 L)", cal: 645, p: 6, c: 51, f: 0, cat: "Beer & Wine" },
  { name: "Beer (strong, 8%)", serving: "1 bottle (650 ml)", cal: 390, p: 3, c: 30, f: 0, cat: "Beer & Wine" },
  { name: "Strong Beer can (8%)", serving: "1 can (500 ml)", cal: 300, p: 2.5, c: 23, f: 0, cat: "Beer & Wine" },
  { name: "Light Beer", serving: "1 bottle (330 ml)", cal: 100, p: 1, c: 6, f: 0, cat: "Beer & Wine" },
  { name: "Wheat Beer / Witbier (craft)", serving: "1 bottle (330 ml)", cal: 155, p: 1.8, c: 14, f: 0, cat: "Beer & Wine" },
  { name: "IPA / Craft Beer (6.5%)", serving: "1 bottle (330 ml)", cal: 200, p: 2, c: 16, f: 0, cat: "Beer & Wine" },
  { name: "Stout", serving: "1 bottle (330 ml)", cal: 180, p: 1.8, c: 15, f: 0, cat: "Beer & Wine" },
  { name: "Non-alcoholic Beer", serving: "1 bottle (330 ml)", cal: 70, p: 1, c: 15, f: 0, cat: "Beer & Wine" },
  { name: "Cider", serving: "1 bottle (330 ml)", cal: 170, p: 0, c: 18, f: 0, cat: "Beer & Wine" },
  { name: "Hard Seltzer", serving: "1 can (330 ml)", cal: 100, p: 0, c: 2, f: 0, cat: "Beer & Wine" },
  { name: "Shandy (beer + lemonade)", serving: "1 glass (330 ml)", cal: 120, p: 0.8, c: 15, f: 0, cat: "Beer & Wine" },
  { name: "Wine (red/white)", serving: "1 glass (150 ml)", cal: 125, p: 0.1, c: 4, f: 0, cat: "Beer & Wine" },
  { name: "Red Wine (large glass)", serving: "1 large glass (250 ml)", cal: 210, p: 0.2, c: 6.5, f: 0, cat: "Beer & Wine" },
  { name: "Wine bottle", serving: "1 bottle (750 ml)", cal: 625, p: 0.5, c: 20, f: 0, cat: "Beer & Wine" },
  { name: "Rosé Wine", serving: "1 glass (150 ml)", cal: 120, p: 0.1, c: 5, f: 0, cat: "Beer & Wine" },
  { name: "Sparkling Wine / Prosecco / Champagne", serving: "1 flute (125 ml)", cal: 90, p: 0.1, c: 2, f: 0, cat: "Beer & Wine" },
  { name: "Port / Dessert Wine", serving: "1 small glass (75 ml)", cal: 120, p: 0.1, c: 10, f: 0, cat: "Beer & Wine" },
  { name: "Sangria", serving: "1 glass (250 ml)", cal: 230, p: 0.3, c: 25, f: 0, cat: "Beer & Wine" },
  { name: "Mulled Wine", serving: "1 mug (200 ml)", cal: 200, p: 0.1, c: 20, f: 0, cat: "Beer & Wine" },
  { name: "Breezer / Alcopop", serving: "1 bottle (275 ml)", cal: 190, p: 0, c: 30, f: 0, cat: "Beer & Wine" },
  { name: "Sake", serving: "1 go (180 ml)", cal: 195, p: 0.9, c: 8, f: 0, cat: "Beer & Wine" },
  { name: "Makgeolli (Korean rice wine)", serving: "1 bowl (250 ml)", cal: 130, p: 2, c: 10, f: 0, cat: "Beer & Wine" },

  { name: "Whisky / Vodka / Rum", serving: "1 peg (30 ml)", cal: 70, p: 0, c: 0, f: 0, cat: "Spirits & Mixers" },
  { name: "Whisky / Vodka / Rum (large)", serving: "1 large peg (60 ml)", cal: 140, p: 0, c: 0, f: 0, cat: "Spirits & Mixers" },
  { name: "Patiala Peg", serving: "1 peg (90 ml)", cal: 210, p: 0, c: 0, f: 0, cat: "Spirits & Mixers" },
  { name: "Gin", serving: "1 peg (30 ml)", cal: 70, p: 0, c: 0, f: 0, cat: "Spirits & Mixers" },
  { name: "Brandy / Cognac", serving: "1 peg (30 ml)", cal: 70, p: 0, c: 0, f: 0, cat: "Spirits & Mixers" },
  { name: "Tequila Shot", serving: "1 shot (45 ml)", cal: 100, p: 0, c: 0, f: 0, cat: "Spirits & Mixers" },
  { name: "Feni (cashew / coconut)", serving: "1 peg (30 ml)", cal: 75, p: 0, c: 0, f: 0, cat: "Spirits & Mixers" },
  { name: "Soju (shot)", serving: "1 soju glass (50 ml)", cal: 50, p: 0, c: 0.5, f: 0, cat: "Spirits & Mixers" },
  { name: "Soju (bottle)", serving: "1 bottle (360 ml, ~17%)", cal: 340, p: 0, c: 4, f: 0, cat: "Spirits & Mixers" },
  { name: "Fruit Soju (peach, grape, etc.)", serving: "1 bottle (360 ml, ~13%)", cal: 340, p: 0, c: 30, f: 0, cat: "Spirits & Mixers" },
  { name: "Fruit Soju (shot)", serving: "1 soju glass (50 ml)", cal: 47, p: 0, c: 4, f: 0, cat: "Spirits & Mixers" },
  { name: "Shochu", serving: "1 serve (60 ml, 25%)", cal: 85, p: 0, c: 0, f: 0, cat: "Spirits & Mixers" },
  { name: "Baijiu", serving: "1 shot (30 ml, 52%)", cal: 90, p: 0, c: 0, f: 0, cat: "Spirits & Mixers" },
  { name: "Jägermeister Shot", serving: "1 shot (30 ml)", cal: 100, p: 0, c: 10, f: 0, cat: "Spirits & Mixers" },
  { name: "Baileys / Cream Liqueur", serving: "1 serve (50 ml)", cal: 160, p: 1, c: 11, f: 7, cat: "Spirits & Mixers" },
  { name: "Coffee Liqueur (Kahlúa)", serving: "1 peg (30 ml)", cal: 90, p: 0, c: 14, f: 0, cat: "Spirits & Mixers" },
  { name: "Whisky Soda / Vodka Soda", serving: "60 ml + soda", cal: 140, p: 0, c: 0, f: 0, cat: "Spirits & Mixers" },
  { name: "Rum and Coke / Cuba Libre", serving: "60 ml rum + 150 ml cola", cal: 205, p: 0, c: 16, f: 0, cat: "Spirits & Mixers" },
  { name: "Whisky / Vodka with Cola", serving: "60 ml + 150 ml cola", cal: 205, p: 0, c: 16, f: 0, cat: "Spirits & Mixers" },
  { name: "Gin and Tonic", serving: "60 ml gin + 150 ml tonic", cal: 190, p: 0, c: 13, f: 0, cat: "Spirits & Mixers" },
  { name: "Vodka Red Bull", serving: "60 ml + 1 can (250 ml)", cal: 255, p: 0, c: 28, f: 0, cat: "Spirits & Mixers" },
  { name: "Vodka with Orange Juice (Screwdriver)", serving: "60 ml + 150 ml juice", cal: 210, p: 1, c: 17, f: 0, cat: "Spirits & Mixers" },
  { name: "Mixer: Cola / Thums Up", serving: "1 glass (200 ml)", cal: 85, p: 0, c: 21, f: 0, cat: "Spirits & Mixers" },
  { name: "Mixer: Tonic Water", serving: "1 glass (200 ml)", cal: 70, p: 0, c: 18, f: 0, cat: "Spirits & Mixers" },
  { name: "Mixer: Ginger Ale", serving: "1 glass (200 ml)", cal: 70, p: 0, c: 18, f: 0, cat: "Spirits & Mixers" },
  { name: "Mixer: Soda Water / Diet Cola", serving: "1 glass (200 ml)", cal: 1, p: 0, c: 0, f: 0, cat: "Spirits & Mixers" },

  { name: "Cocktail (sweet, e.g. mojito/margarita)", serving: "1 glass", cal: 220, p: 0, c: 25, f: 0, cat: "Cocktails" },
  { name: "Mojito", serving: "1 glass", cal: 220, p: 0, c: 25, f: 0, cat: "Cocktails" },
  { name: "Virgin Mojito (mocktail)", serving: "1 glass", cal: 120, p: 0, c: 30, f: 0, cat: "Cocktails" },
  { name: "Margarita", serving: "1 glass", cal: 270, p: 0, c: 20, f: 0, cat: "Cocktails" },
  { name: "Frozen / Fruit Margarita", serving: "1 large glass", cal: 350, p: 0, c: 45, f: 0, cat: "Cocktails" },
  { name: "Piña Colada", serving: "1 glass", cal: 450, p: 1, c: 55, f: 12, cat: "Cocktails" },
  { name: "Long Island Iced Tea", serving: "1 glass", cal: 280, p: 0, c: 33, f: 0, cat: "Cocktails" },
  { name: "Cosmopolitan", serving: "1 glass", cal: 150, p: 0, c: 10, f: 0, cat: "Cocktails" },
  { name: "Martini (gin / vodka)", serving: "1 glass", cal: 175, p: 0, c: 1, f: 0, cat: "Cocktails" },
  { name: "Espresso Martini", serving: "1 glass", cal: 230, p: 0, c: 20, f: 0, cat: "Cocktails" },
  { name: "Old Fashioned", serving: "1 glass", cal: 160, p: 0, c: 5, f: 0, cat: "Cocktails" },
  { name: "Whisky Sour", serving: "1 glass", cal: 170, p: 1, c: 12, f: 0, cat: "Cocktails" },
  { name: "Negroni", serving: "1 glass", cal: 200, p: 0, c: 15, f: 0, cat: "Cocktails" },
  { name: "Aperol Spritz", serving: "1 glass", cal: 160, p: 0, c: 14, f: 0, cat: "Cocktails" },
  { name: "Moscow Mule", serving: "1 glass", cal: 180, p: 0, c: 18, f: 0, cat: "Cocktails" },
  { name: "Daiquiri (classic)", serving: "1 glass", cal: 190, p: 0, c: 15, f: 0, cat: "Cocktails" },
  { name: "Strawberry Daiquiri (frozen)", serving: "1 glass", cal: 300, p: 0.5, c: 40, f: 0, cat: "Cocktails" },
  { name: "Sex on the Beach", serving: "1 glass", cal: 250, p: 0, c: 25, f: 0, cat: "Cocktails" },
  { name: "Blue Lagoon", serving: "1 glass", cal: 200, p: 0, c: 22, f: 0, cat: "Cocktails" },
  { name: "Tequila Sunrise", serving: "1 glass", cal: 230, p: 0.5, c: 25, f: 0, cat: "Cocktails" },
  { name: "Mai Tai", serving: "1 glass", cal: 270, p: 0, c: 25, f: 0, cat: "Cocktails" },
  { name: "Caipirinha / Caipiroska", serving: "1 glass", cal: 240, p: 0, c: 25, f: 0, cat: "Cocktails" },
  { name: "Bloody Mary", serving: "1 glass", cal: 130, p: 1, c: 9, f: 0, cat: "Cocktails" },
  { name: "White Russian", serving: "1 glass", cal: 300, p: 2, c: 15, f: 12, cat: "Cocktails" },
  { name: "Irish Coffee", serving: "1 glass", cal: 220, p: 1, c: 15, f: 9, cat: "Cocktails" },
  { name: "Mimosa / Bellini", serving: "1 flute (150 ml)", cal: 110, p: 0.2, c: 10, f: 0, cat: "Cocktails" },
  { name: "Somaek (soju + beer)", serving: "1 glass (50 ml soju + 150 ml beer)", cal: 115, p: 0.7, c: 5.5, f: 0, cat: "Cocktails" },
  { name: "Yogurt Soju (Yakult soju)", serving: "1 glass (200 ml)", cal: 190, p: 1, c: 22, f: 0, cat: "Cocktails" },
  { name: "Kokum / Jamun Feni Cocktail", serving: "1 glass", cal: 200, p: 0, c: 20, f: 0, cat: "Cocktails" },
];
